//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support_CounterService_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DEC
    {
        public string REF_NO { get; set; }
        public string JOB_NO { get; set; }
        public string H_INV_NO { get; set; }
        public string USERNAME { get; set; }
        public string CM_CODE { get; set; }
        public string CC_CODE { get; set; }
        public string CS_CODE { get; set; }
        public string DOC_TYPE { get; set; }
        public string TRAN_TYPE { get; set; }
        public string CG_TYPE { get; set; }
        public string VES_NAME { get; set; }
        public Nullable<System.DateTime> ARR_DATE { get; set; }
        public string MBL_NO { get; set; }
        public string HBL_NO { get; set; }
        public string OR_PORT { get; set; }
        public string RL_PORT { get; set; }
        public string DC_PORT { get; set; }
        public string O_COUN { get; set; }
        public string C_COUN { get; set; }
        public string SHIP_MARK { get; set; }
        public Nullable<int> TOT_PACK { get; set; }
        public string TOT_PACK_U { get; set; }
        public Nullable<decimal> N_WEIGHT { get; set; }
        public string N_WEIGHT_U { get; set; }
        public Nullable<decimal> G_WEIGHT { get; set; }
        public string G_WEIGHT_U { get; set; }
        public string CURR_CODE { get; set; }
        public Nullable<decimal> EXC_RATE { get; set; }
        public Nullable<decimal> CIF_F { get; set; }
        public Nullable<decimal> CIF_B { get; set; }
        public string RGS_CODE { get; set; }
        public string CBK_CODE { get; set; }
        public string BK_CODE { get; set; }
        public string BK_B_CODE { get; set; }
        public string BK_A_NO { get; set; }
        public Nullable<decimal> TOT_PAY_AMT { get; set; }
        public string PAY_MT { get; set; }
        public Nullable<decimal> TOT_TAX_P { get; set; }
        public Nullable<decimal> TOT_DPS { get; set; }
        public string REF_ASS { get; set; }
        public string ASS_CODE { get; set; }
        public string INS_CODE { get; set; }
        public Nullable<System.DateTime> DEPAR_DATE { get; set; }
        public string APP_PORT { get; set; }
        public string APP_NO { get; set; }
        public string GRT_MT { get; set; }
        public string GRT_TYPE { get; set; }
        public string GRT_BK_CODE { get; set; }
        public string GRT_BK_B_CODE { get; set; }
        public string GRT_BK_A_NO { get; set; }
        public Nullable<decimal> GRT_DPS_AMT { get; set; }
        public string EXP_TAX_IN_ID { get; set; }
        public string CTP_TAX_NO { get; set; }
        public string CTP_B_CODE { get; set; }
        public string DEF_PAY { get; set; }
        public string TCARD_BK_CODE { get; set; }
        public string TCARD_BK_B_CODE { get; set; }
        public string TCARD_BK_A_CODE { get; set; }
        public Nullable<decimal> TCARD_TOT_PAY { get; set; }
        public string REG_ID { get; set; }
        public string REF_XML { get; set; }
        public string SIGN_BY { get; set; }
        public string DECSNO { get; set; }
        public Nullable<System.DateTime> PAY_EFT_D { get; set; }
        public string PAY_EFT_N { get; set; }
        public string SENDEDI { get; set; }
        public string FRESPONS_M { get; set; }
        public string DEC_CANCEL { get; set; }
        public string DEC_CANC_M { get; set; }
        public Nullable<System.DateTime> DATE_T { get; set; }
        public string FOR_CURR { get; set; }
        public Nullable<decimal> FOR_F { get; set; }
        public string FRI_CURR { get; set; }
        public Nullable<decimal> FRI_F { get; set; }
        public string INS_CURR { get; set; }
        public Nullable<decimal> INS_F { get; set; }
        public string PACK_CURR { get; set; }
        public Nullable<decimal> PACK_F { get; set; }
        public string INL_CURR { get; set; }
        public Nullable<decimal> INL_F { get; set; }
        public string LAN_CURR { get; set; }
        public Nullable<decimal> LAN_F { get; set; }
        public string OTH_CURR { get; set; }
        public Nullable<decimal> OTH_F { get; set; }
        public Nullable<decimal> TOT_IMD { get; set; }
        public Nullable<decimal> TOT_IMD_DPS { get; set; }
        public Nullable<decimal> TOT_EXC { get; set; }
        public Nullable<decimal> TOT_EXC_DPS { get; set; }
        public Nullable<decimal> TOT_LOC { get; set; }
        public Nullable<decimal> TOT_LOC_DPS { get; set; }
        public Nullable<decimal> TOT_VAT { get; set; }
        public Nullable<decimal> TOT_VAT_DPS { get; set; }
        public Nullable<decimal> TOT_OTH { get; set; }
        public Nullable<decimal> TOT_OTH_DPS { get; set; }
        public string ESTIBIS_N { get; set; }
        public string FACTORY_N { get; set; }
        public string F_PRINT { get; set; }
        public string DESCRIPT_M { get; set; }
        public string AVG_TYPE { get; set; }
        public string AVG_OTH { get; set; }
        public string CON_REF { get; set; }
        public string EDIT_USER { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string AVG_INV { get; set; }
        public string AUDITOR_N { get; set; }
        public string AVG_ALL { get; set; }
        public string WEB_CONFIRM_S { get; set; }
        public Nullable<System.DateTime> ACCEPT_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public Nullable<decimal> TOT_FEE { get; set; }
    }
}
