//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support_CounterService_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDEC_A
    {
        public string REFNO { get; set; }
        public string RUNNO { get; set; }
        public string CMCODE { get; set; }
        public string BCMCODE { get; set; }
        public string CCARD { get; set; }
        public string MCARD { get; set; }
        public string REFXML { get; set; }
        public string INVNO { get; set; }
        public string TRANSPORT_M { get; set; }
        public string CARGO_TYPE { get; set; }
        public string VESSEL_N { get; set; }
        public Nullable<System.DateTime> DEPART_DATE { get; set; }
        public string MASTER_BL { get; set; }
        public string HOUSE_BL { get; set; }
        public string ESTABLISH_N { get; set; }
        public string FACTORY_N { get; set; }
        public string RELEASE_P { get; set; }
        public string LOAD_P { get; set; }
        public string DISCHAR_P { get; set; }
        public string PURCHASE_C { get; set; }
        public string DEST_C { get; set; }
        public string SHIP_MARK { get; set; }
        public Nullable<decimal> TOTPACK { get; set; }
        public string TOTPACK_U { get; set; }
        public Nullable<decimal> TOTNET { get; set; }
        public string TOTNET_U { get; set; }
        public Nullable<decimal> TOTGROSS { get; set; }
        public string TOTGROSS_U { get; set; }
        public string CURR_CODE { get; set; }
        public Nullable<decimal> EXCH_R { get; set; }
        public Nullable<decimal> TOTFOB_F { get; set; }
        public Nullable<decimal> TOTFOB_B { get; set; }
        public string RGS { get; set; }
        public string CUSTOM_BANKCODE { get; set; }
        public string CM_BANKID { get; set; }
        public Nullable<decimal> TOT_PAYMENT_AMT { get; set; }
        public string PAY_METHOD { get; set; }
        public Nullable<decimal> TOT_TAX { get; set; }
        public Nullable<decimal> TOT_DEPOSIT { get; set; }
        public string COMMOM_ACCESS { get; set; }
        public string ASSESSMENT_R { get; set; }
        public string INSPECT_R { get; set; }
        public string GUARANTEE_METHOD { get; set; }
        public string GUARANTEE_TYPE { get; set; }
        public string GUARANTEE_BANKCODE { get; set; }
        public Nullable<decimal> GUARANTEE_TOT_DEPOSIT { get; set; }
        public string EXPORT_INTENSIVE_ID { get; set; }
        public string TRADE_PARTNER_TAX { get; set; }
        public string TRADE_PARTNER_BRANCH { get; set; }
        public string SUB_BROKER_TAX { get; set; }
        public string DEFERRED_PAYMENT { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public Nullable<System.DateTime> ACCEPT_DATE { get; set; }
        public Nullable<System.DateTime> CLEAR_DATE { get; set; }
        public Nullable<System.DateTime> LOAD_DATE { get; set; }
        public string CANCEL_S { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public string STATUS { get; set; }
        public string DECLARATION_NO { get; set; }
        public string USERNAME { get; set; }
        public string BACK_PAPER_NOTE { get; set; }
        public string SIGN_DEC_BY { get; set; }
        public string SIGN_GOOD_BY { get; set; }
        public string DOC_TYPE { get; set; }
        public string CHECK_RECIEVE_BACK { get; set; }
        public string REFSHORT { get; set; }
        public string REFSHORT_CUSTOMS { get; set; }
        public Nullable<int> SHORT_TOTPACK { get; set; }
        public string SHORT_STATUS { get; set; }
        public string SHORT_USER { get; set; }
        public Nullable<System.DateTime> SHORT_LASTUPDATE { get; set; }
        public string REFSHORTPOST { get; set; }
        public string REFSHORTPOST_CUSTOMS { get; set; }
        public Nullable<int> SHORTPOST_TOTPACK { get; set; }
        public string SHORTPOST_USER { get; set; }
        public Nullable<System.DateTime> SHORTPOST_LASTUPDATE { get; set; }
        public Nullable<decimal> TOTQTY { get; set; }
        public string TOTQTY_U { get; set; }
        public Nullable<decimal> DETAILFOB_VF { get; set; }
        public Nullable<decimal> DETAILFOB_VB { get; set; }
        public string CUSTOMS_MSG { get; set; }
        public string COMPANY_L { get; set; }
        public string CUSTOMS_CONT_MSG { get; set; }
        public Nullable<System.DateTime> EXPORT_DATE { get; set; }
        public string PROFILE { get; set; }
        public string CANCEL_MSG { get; set; }
        public string COMPEN_ID { get; set; }
        public Nullable<decimal> SHORT_TOTNET { get; set; }
        public Nullable<decimal> SHORT_TOTGROSS { get; set; }
        public Nullable<decimal> SHORTPOST_TOTNET { get; set; }
        public Nullable<decimal> SHORTPOST_TOTGROSS { get; set; }
        public string CM_TAX { get; set; }
        public string CM_BRANCH { get; set; }
        public string CM_THAI { get; set; }
        public string CM_ENG { get; set; }
        public string CM_STREET { get; set; }
        public string CM_DISTRICT { get; set; }
        public string CM_SUBPROVINCE { get; set; }
        public string CM_PROVINCE { get; set; }
        public string CM_POSTCODE { get; set; }
        public string VOY { get; set; }
        public string CM_PHONE { get; set; }
        public string CM_FAX { get; set; }
        public string WEB_STATUS { get; set; }
        public string WEB_REASON { get; set; }
        public string SPECIAL_REMARK { get; set; }
        public string CUTLIST { get; set; }
        public Nullable<System.DateTime> CUTDATE { get; set; }
        public Nullable<System.DateTime> CUTLIST_PRINTDATE { get; set; }
        public string CHECK_AUDIT { get; set; }
        public string CHECK_TRANFER { get; set; }
    }
}
